### ISSUE TITLE
Error: Invalid --tag default for the selected package

### ISSUE THREAD

**Issue by nicolas71640** [docker-android-sdk/android-26#1]
I have been using this docker image for few weeks, and it was working well until last week... 
I've got this error when I'm trying to create and avd : " Error: Invalid --tag default for the selected package ". I've found this post [](https://stackoverflow.com/questions/48143362/avdmanager-error-invalid-tag-default-for-the-selected-package). So I've added this argument : --abi google_apis/x86, so my command becomes 

`"create avd -n first_avd --abi google_apis/x86_64 -k  "system-images;android-26;google_apis;x86_64"`

Seems to work fine until I try to launch the emulator with this command :  

`emulator -avd first_avd -no-window -no-audio -dns-server 8.8.8.8 &` 

which returns this error :

 `PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [/opt/android-sdk-linux]!`

Have you experienced this issue already ?

**Comment by ppoffice** [comment]
@nicolas71640 I guess you have built it from the Dockerfile instead of using the prebuilt docker hub image. I have updated the Dockerfile and it should work now.

**Comment by nicolas71640** [comment]
It works, thanks !
